// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.72_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/node_modules/.pnpm/@umijs+renderer-react@4.0.72_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/node_modules/.pnpm/umi@4.0.72_@babel+core@7.22.8_@types+react@18.2.14_eslint@8.35.0_postcss@8.4.25_prettier@3.0._mivl5mm5qh2xk3cwkdr5y7i7qq/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-access';
export { Provider, useModel } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-model';
export { MicroApp, MicroAppWithMemoHistory } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-qiankun-master';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-access/types.d';
export * from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-antd/types.d';
export * from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-layout/types.d';
export * from '/Users/liangchaofei/Desktop/dd/micro/main-demo/src/.umi/plugin-request/types.d';
